### ISSUE TITLE
disclaim_bench hangs sometimes in wait_marker (musl, parallel marker enabled)

### ISSUE THREAD

**Issue by ivmai** [ivmai/bdwgc#169]
How to reproduce:
CC=musl-gcc ./configure --enable-werror && make -j check
run disclaim_bench several times.

Host: Ubuntu 16.04 LTS / x86_64, 32 cores.
Musl version: 0.9.15-1

i.maidanski@alduin:~/bdwgc$ sudo dpkg-query -l | grep "musl"
ii  musl:amd64                             0.9.15-1
      amd64        standard C library
ii  musl-dev                               0.9.15-1
      amd64        standard C library development files
ii  musl-tools                             0.9.15-1
      amd64        standard C library tools

stack trace:
#0  0x00007ffff7dc8a73 in __syscall_cp () from /lib/ld-musl-x86_64.so.1
#1  0x00007ffff7dc88e3 in __timedwait () from /lib/ld-musl-x86_64.so.1
#2  0x00007ffff7dc94ef in pthread_cond_timedwait ()
   from /lib/ld-musl-x86_64.so.1
#3  0x00007ffff7b2bae7 in GC_wait_marker () at pthread_support.c:2158
#4  0x00007ffff7b21f05 in GC_mark_local (
    local_mark_stack=0x7ffff7d48268 <mark_cv+8>,
    local_mark_stack@entry=0x7ffffffee370, id=id@entry=0) at mark.c:1140
#5  0x00007ffff7b2211f in GC_do_parallel_mark () at mark.c:1209
#6  0x00007ffff7b2313d in GC_mark_some (
    cold_gc_frame=0x7fffffffe3d0 "|w\324\367\377\177") at mark.c:395
#7  0x00007ffff7b192cd in GC_stopped_mark (
    stop_func=0x7ffff7b18d60 <GC_never_stop_func>) at alloc.c:702
#8  0x00007ffff7b19dba in GC_try_to_collect_inner (
    stop_func=0x7ffff7b18d60 <GC_never_stop_func>) at alloc.c:488
#9  0x00007ffff7b1a782 in GC_collect_or_expand (
    needed_blocks=needed_blocks@entry=1,
    ignore_off_page=ignore_off_page@entry=0, retry=retry@entry=0)
    at alloc.c:1348
#10 0x00007ffff7b1a972 in GC_allocobj (gran=gran@entry=4, kind=1)
    at alloc.c:1443
#11 0x00007ffff7b1fc5b in GC_generic_malloc_inner (lb=lb@entry=48,
    k=k@entry=1) at malloc.c:143
#12 0x00007ffff7b1db6a in GC_register_finalizer_inner (obj=0x7ffff71a3930,
...

(gdb) frame 3
#3  0x00007ffff7b2bae7 in GC_wait_marker () at pthread_support.c:2158
2158        if (pthread_cond_wait(&mark_cv, &mark_mutex) != 0) {
(gdb) p mark_cv
$1 = {__u = {__i = {-137067808, 32767, 6183, 10, 0, 0, 0, 6, 0, 0, 0, 0},
    __p = {0x7ffff7d482e0 <mark_mutex>, 0xa00001827, 0x0, 0x600000000, 0x0,
      0x0}}}
(gdb) p mark_mutex
$2 = {__u = {__i = {0, 0, 10, 0, 0, 0, 0, 0, 0, 0}, __p = {0x0, 0xa, 0x0,
      0x0, 0x0}}}

**Comment by ivmai** [comment]
Cannot reproduce with musl v1.1.16.
