### ISSUE TITLE
gctest hang if compiled with TSan (Linux)

### ISSUE THREAD

**Issue by ivmai** [ivmai/bdwgc#181]
How to reproduce:
./configure --disable-parallel-mark && make -j check CC=clang-4.0 CFLAGS_EXTRA="-fsanitize=thread -DNO_CANCEL_SAFE -DDEBUG_THREADS"

Host: Ubuntu/x64
Source: master branch

The reason: signals are not delivered.
I found a topic about signals delivery in Thread Sanitizer: https://groups.google.com/forum/#!topic/thread-sanitizer/xtSQQQPcIfs

**Comment by ivmai** [comment]
Build link: https://travis-ci.org/ivmai/bdwgc/jobs/310827153

**Comment by ivmai** [comment]
gctest hang still occurs sometimes:

(gdb) info threads
  Id   Target Id         Frame
  27   Thread 0x7f2bf5eff700 (LWP 16955) "exe" 0x00007f2bf7120d4d in nanosleep () at ../sysdeps/unix/syscall-template.S:81
  26   Thread 0x7f2bf3aff700 (LWP 16969) "exe" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  25   Thread 0x7f2bf1afe700 (LWP 16970) "exe" __lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
  24   Thread 0x7f2bef8ff700 (LWP 16971) "exe" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  23   Thread 0x7f2bed8fe700 (LWP 16972) "exe" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  22   Thread 0x7f2beb8fd700 (LWP 16973) "exe" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  21   Thread 0x7f2be98fc700 (LWP 16974) "exe" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  20   Thread 0x7f2be78fb700 (LWP 16975) "exe" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  19   Thread 0x7f2be58fa700 (LWP 16976) "exe" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  18   Thread 0x7f2be36ff700 (LWP 16977) "exe" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  17   Thread 0x7f2be16fe700 (LWP 16978) "exe" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  16   Thread 0x7f2bdf6fd700 (LWP 16980) "exe" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  15   Thread 0x7f2bdd6fc700 (LWP 16981) "exe" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  14   Thread 0x7f2bdb6fb700 (LWP 16982) "exe" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  13   Thread 0x7f2bd96fa700 (LWP 16983) "exe" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  12   Thread 0x7f2bd76f9700 (LWP 16984) "exe" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  11   Thread 0x7f2bd56f8700 (LWP 16986) "exe" 0x000000000049897e in __sanitizer::BlockingMutex::Lock() ()
  10   Thread 0x7f2bd36f7700 (LWP 16987) "exe" 0x000000000049897e in __sanitizer::BlockingMutex::Lock() ()
  9    Thread 0x7f2bd14ff700 (LWP 16988) "exe" 0x000000000049897e in __sanitizer::BlockingMutex::Lock() ()
  8    Thread 0x7f2bcf4fe700 (LWP 16989) "exe" 0x000000000049897e in __sanitizer::BlockingMutex::Lock() ()
  7    Thread 0x7f2bcd4fd700 (LWP 16990) "exe" 0x000000000049897e in __sanitizer::BlockingMutex::Lock() ()
  6    Thread 0x7f2bcb4fc700 (LWP 16992) "exe" 0x000000000049897e in __sanitizer::BlockingMutex::Lock() ()
  5    Thread 0x7f2bc94fb700 (LWP 16993) "exe" 0x000000000049897e in __sanitizer::BlockingMutex::Lock() ()
  4    Thread 0x7f2bc74fa700 (LWP 16994) "exe" 0x000000000049897e in __sanitizer::BlockingMutex::Lock() ()
  3    Thread 0x7f2bc54f9700 (LWP 16995) "exe" 0x000000000049897e in __sanitizer::BlockingMutex::Lock() ()
  2    Thread 0x7f2bc34f8700 (LWP 16996) "exe" 0x000000000049897e in __sanitizer::BlockingMutex::Lock() ()
* 1    Thread 0x7f2bf816eb40 (LWP 16909) "exe" 0x000000000049897e in __sanitizer::BlockingMutex::Lock() ()
(gdb) t 1
[Switching to thread 1 (Thread 0x7f2bf816eb40 (LWP 16909))]
#0  0x000000000049897e in __sanitizer::BlockingMutex::Lock() ()
(gdb) bt
#0  0x000000000049897e in __sanitizer::BlockingMutex::Lock() ()
#1  0x00000000004849f1 in __tsan::AfterSleep(__tsan::ThreadState*, unsigned long) ()
#2  0x000000000044ba07 in nanosleep ()
#3  0x00000000004dcb28 in GC_lock () at pthread_support.c:2090
#4  0x00000000004dc856 in GC_is_thread_tsd_valid (tsd=0x15af6e0 <first_thread+136>) at pthread_support.c:689
#5  0x00000000004e2750 in GC_malloc_kind (bytes=0, knd=0) at thread_local_alloc.c:182
#6  0x00000000004c4d8c in GC_malloc_atomic (lb=9637080) at malloc.c:355
#7  0x00000000004b37a6 in run_one_test () at tests/test.c:1414
#8  0x00000000004b4c0b in main () at tests/test.c:2280
(gdb) t 25
[Switching to thread 25 (Thread 0x7f2bf1afe700 (LWP 16970))]
#0  __lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
135     ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S: No such file or directory.
(gdb) bt
#0  __lll_lock_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007f2bf7d603f8 in _L_cond_lock_886 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f2bf7d60164 in __pthread_mutex_cond_lock (mutex=0x15afa48 <mark_mutex>) at ../nptl/pthread_mutex_lock.c:79
#3  0x00007f2bf7d5a494 in pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:259
#4  0x000000000048d1e8 in __tsan::call_pthread_cancel_with_cleanup(int (*)(void*, void*, void*), void*, void*, void*, void (*)(void*), void*) ()
#5  0x000000000042417c in cond_wait(__tsan::ThreadState*, unsigned long, __tsan::ScopedInterceptor*, int (*)(void*, void*, void*), void*, void*, void*) [clone .constprop.90] ()
#6  0x000000000044f4f4 in pthread_cond_wait ()
#7  0x00000000004e0789 in GC_wait_marker () at pthread_support.c:2249
#8  0x00000000004c9d64 in GC_help_marker (my_mark_no=5) at mark.c:1260
#9  0x00000000004dbac4 in GC_mark_thread (id=<optimized out>) at pthread_support.c:379
#10 0x00000000004216ac in __tsan_thread_start_func ()
#11 0x00007f2bf7d56184 in start_thread (arg=0x7f2bf1afe700) at pthread_create.c:312
#12 0x00007f2bf7159ffd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb) t 26
[Switching to thread 26 (Thread 0x7f2bf3aff700 (LWP 16969))]
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
185     ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S: No such file or directory.
(gdb) bt
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x000000000048d1e8 in __tsan::call_pthread_cancel_with_cleanup(int (*)(void*, void*, void*), void*, void*, void*, void (*)(void*), void*) ()
#2  0x000000000042417c in cond_wait(__tsan::ThreadState*, unsigned long, __tsan::ScopedInterceptor*, int (*)(void*, void*, void*), void*, void*, void*) [clone .constprop.90] ()
#3  0x000000000044f4f4 in pthread_cond_wait ()
#4  0x00000000004e0789 in GC_wait_marker () at pthread_support.c:2249
#5  0x00000000004c9d64 in GC_help_marker (my_mark_no=6) at mark.c:1260
#6  0x00000000004dbac4 in GC_mark_thread (id=<optimized out>) at pthread_support.c:379
#7  0x00000000004216ac in __tsan_thread_start_func ()
#8  0x00007f2bf7d56184 in start_thread (arg=0x7f2bf3aff700) at pthread_create.c:312
#9  0x00007f2bf7159ffd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

**Comment by ivmai** [comment]
Fixed.

**Comment by ivmai** [comment]
Still happens (on master). One thread is busy waiting in retry loop of GC_stop_world, the rest threads hang in sigsuspend,

**Comment by ivmai** [comment]
Observed on the latest master: https://travis-ci.org/ivmai/bdwgc/jobs/333495385

**Comment by ivmai** [comment]
Latest fail: https://travis-ci.org/ivmai/bdwgc/jobs/357279589

**Comment by ivmai** [comment]
Also observed with MSan: https://travis-ci.org/ivmai/bdwgc/jobs/359743820

**Comment by ivmai** [comment]
This issue should be fixed now.
