### ISSUE TITLE
gctest hangs sometimes if compiled with TSan

### ISSUE THREAD

**Issue by ivmai** [ivmai/bdwgc#236]
Build link: https://travis-ci.org/ivmai/bdwgc/jobs/425865116

Source master (or 8.0.0)
Host: Linux/x64

How to build and run: ./configure --disable-parallel-mark && make check CFLAGS_EXTRA="-fsanitize=thread -D NO_CANCEL_SAFE -D NO_INCREMENTAL -D USE_SPIN_LOCK -fno-omit-frame-pointer -D NTHREADS=15"

**Comment by ivmai** [comment]
Reproduced on latest master (a8c5ee41a)
Build link: https://travis-ci.org/ivmai/bdwgc/jobs/523219610

**Comment by ivmai** [comment]
Reproduced on latest master (dd1d0bc)
Build link: https://travis-ci.com/github/ivmai/bdwgc/jobs/529655035

**Comment by ivmai** [comment]
Reproduced on latest master (a6e21c52).
Builds:
* https://app.travis-ci.com/github/ivmai/bdwgc/jobs/562212707
* https://app.travis-ci.com/github/ivmai/bdwgc/jobs/562212709
* https://app.travis-ci.com/github/ivmai/bdwgc/jobs/562212710

**Comment by ivmai** [comment]
Note: latest successful build - https://app.travis-ci.com/github/ivmai/bdwgc/builds/247123548 (e700c78)

**Comment by ivmai** [comment]
Build: https://app.travis-ci.com/github/ivmai/bdwgc/jobs/564340350
Source: master (7aa23f4)
gctest hang.

**Comment by ivmai** [comment]
Source: master (https://github.com/ivmai/bdwgc/commit/7aa23f4e849520c229ea3c26d84afd39ebe83711)

Build: https://app.travis-ci.com/github/ivmai/bdwgc/jobs/564340350
gctest hang.

**Comment by ivmai** [comment]
Build: https://app.travis-ci.com/github/ivmai/bdwgc/jobs/565405309
Source: master (0eb8d2f9)

**Comment by ivmai** [comment]
Build: https://app.travis-ci.com/github/ivmai/bdwgc/jobs/565562062
Source: master (e34da92557)

**Comment by ivmai** [comment]
gctest still hangs sometimes (even after commit 
ba0616b).

**Comment by ivmai** [comment]
Not reproduced if GC_ENABLE_SUSPEND_THREAD is undefined.

**Comment by ivmai** [comment]
Latest build: https://app.travis-ci.com/github/ivmai/bdwgc/jobs/566687404
Source: master (09dd6a6)

**Comment by ivmai** [comment]
The issue is still reproduced rarely, e.g.:
```
(gdb) t 18
#0  0x00000000004a0067 in __sanitizer::internal_sched_yield() ()
#1  0x000000000047ec45 in __tsan::Mutex::Lock() ()
#2  0x00000000004957a7 in __tsan::MetaMap::GetAndLock(__tsan::ThreadState*, unsigned long, unsigned long, bool, bool) ()
#3  0x000000000048dad5 in __tsan::MutexUnlock(__tsan::ThreadState*, unsigned long, unsigned long, unsigned int) ()
#4  0x0000000000443ca0 in pthread_mutex_unlock ()
#5  0x00000000004ea041 in GC_suspend_thread (thread=<optimized out>) at pthread_stop_world.c:650
#6  0x00000000004b82be in fork_a_thread () at tests/gctest.c:657


(gdb) t 23
#0  0x00007f7f5a5524ba in __GI___sigsuspend (set=0xfed438 <suspend_handler_mask>)
    at ../sysdeps/unix/sysv/linux/sigsuspend.c:26
#1  0x000000000042c485 in sigsuspend ()
#2  0x00000000004e9a8a in GC_suspend_handler_inner (dummy=<optimized out>, context=<optimized out>)
    at pthread_stop_world.c:396
#3  0x00000000004e98ae in GC_suspend_sigaction (sig=<optimized out>, info=<optimized out>, context=<optimized out>)
    at pthread_stop_world.c:276
#4  0x000000000042c96c in __tsan::CallUserSignalHandler(__tsan::ThreadState*, bool, bool, bool, int, __sanitizer::__sanitizer_siginfo*, void*) ()
#5  0x000000000046459c in rtl_sigaction(int, __sanitizer::__sanitizer_siginfo*, void*) ()
#6  <signal handler called>
#7  0x0000000000499217 in __sanitizer::DD::MutexBeforeLock(__sanitizer::DDCallback*, __sanitizer::DDMutex*, bool) ()
#8  0x000000000048d210 in __tsan::MutexPreLock(__tsan::ThreadState*, unsigned long, unsigned long, unsigned int) ()
#9  0x0000000000443b10 in pthread_mutex_lock ()
#10 0x00000000004e8fae in GC_generic_lock (lock=0xfec6d0 <GC_allocate_ml>) at pthread_support.c:2354
#11 0x00000000004e4b03 in GC_lock () at pthread_support.c:2454
```

Unclear how to workaround this.

**Comment by ivmai** [comment]
Latest build (hang): https://app.travis-ci.com/github/ivmai/bdwgc/jobs/567979958
Source: master (fd4e579)

**Comment by ivmai** [comment]
Latest build: https://app.travis-ci.com/github/ivmai/bdwgc/jobs/573526977
Source: b75f1aa (master)

**Comment by ivmai** [comment]
Build: https://app.travis-ci.com/github/ivmai/bdwgc/jobs/576835719
Source: release-8_2 (4919305150)

**Comment by ivmai** [comment]
Build: https://app.travis-ci.com/github/ivmai/bdwgc/jobs/588637564
Source: release-8_2 (2b342c4)

**Comment by ivmai** [comment]
How to reproduce locally:
./configure --enable-werror --enable-gc-assertions --disable-shared
check CFLAGS_EXTRA="-O0 -g -fsanitize=thread -fno-omit-frame-pointer"
GC_PRINT_STATS=1 gdb ./gctest

**Comment by ivmai** [comment]
Cannot reproduce locally on this config (as of commit 6dfd81e on master):
./configure --enable-werror --enable-gc-assertions --disable-shared
make -j check CFLAGS_EXTRA="-O0 -g -fsanitize=thread -fno-omit-frame-pointer"
GC_PRINT_STATS=1 gdb ./gctest

**Comment by ivmai** [comment]
Source: release-8_2 (bef858c)
Build 1: https://app.travis-ci.com/github/ivmai/bdwgc/jobs/601194806
Build 2: https://app.travis-ci.com/github/ivmai/bdwgc/jobs/601194807
Host: Ubuntu 16.04.7 LTS / x64
Compiler: clang version 7.0.0 (tags/RELEASE_700/final)
Config 1: CFLAGS_EXTRA="-fsanitize=thread -D NO_CANCEL_SAFE -D NO_INCREMENTAL -D USE_SPIN_LOCK -fno-omit-frame-pointer -D TEST_FORK_WITHOUT_ATFORK" CONF_OPTIONS="--enable-gc-assertions --enable-gc-debug --enable-handle-fork=manual --enable-large-config --with-libatomic-ops=no"
Config 2: CFLAGS_EXTRA="-fsanitize=thread -D NO_CANCEL_SAFE -D NO_INCREMENTAL -D USE_SPIN_LOCK -fno-omit-frame-pointer -D NTHREADS=15" CONF_OPTIONS="--disable-parallel-mark"

**Comment by ivmai** [comment]
Build: https://app.travis-ci.com/github/ivmai/bdwgc/jobs/609522449
Source: release-8_2 (399005e)
Host: Ubuntu 16.04.7 LTS / amd64
Compiler: clang version 7.0.0 (tags/RELEASE_700/final)
Config: CFLAGS_EXTRA="-fsanitize=thread -D NO_CANCEL_SAFE -D NO_INCREMENTAL -D USE_SPIN_LOCK -fno-omit-frame-pointer -D NTHREADS=15" CONF_OPTIONS="--disable-parallel-mark"

**Comment by ivmai** [comment]
Source: release-8_2 (2e06a6f)
Build: https://app.travis-ci.com/github/bdwgc/bdwgc/jobs/639523740
Host: Ubuntu 16.04.7 LTS / x86_64
Config: `CFLAGS_EXTRA="-fsanitize=thread -D NO_CANCEL_SAFE -D NO_INCREMENTAL -D USE_SPIN_LOCK -fno-omit-frame-pointer -D NTHREADS=15" CONF_OPTIONS="--disable-parallel-mark"`
