### ISSUE TITLE
SIGSEGV in threadkey_test

### ISSUE THREAD

**Issue by ivmai** [ivmai/bdwgc#238]
Host: Ubuntu/x64
Compiler: gcc-5.5.0
Source: latest master (0c0e4cd)

How to reproduce:
* ./configure --enable-gc-assertions --disable-munmap && make check CFLAGS_EXTRA="-O3 -march=native"
* run gctest in a loop in a terminal (parallel to threadkey_test)
* run threadkey_test in a loop (500-1000 runs)

**Comment by ivmai** [comment]
Program terminated with signal SIGSEGV, Segmentation fault.
\#0  __pthread_create_2_1 (newthread=newthread@entry=0x7fac337f5e48, attr=attr@entry=0x7fac337f5e50,
    start_routine=start_routine@entry=0x7fac82bcec80 <GC_start_routine>, arg=arg@entry=0x82f8c0)
    at pthread_create.c:713

(gdb) bt
\#0  __pthread_create_2_1 (newthread=newthread@entry=0x7fac337f5e48, attr=attr@entry=0x7fac337f5e50,
    start_routine=start_routine@entry=0x7fac82bcec80 <GC_start_routine>, arg=arg@entry=0x82f8c0)
    at pthread_create.c:713
\# 1  0x00007fac82bdece4 in GC_pthread_create (new_thread=0x7fac337f5e48, attr=0x7fac337f5e50,
    start_routine=<optimized out>, arg=<optimized out>) at extra/../pthread_support.c:1900
\# 2  0x0000000000400e8a in on_thread_exit_inner (sb=<optimized out>, arg=<optimized out>) at tests/threadkey_test.c:71

**Comment by ivmai** [comment]
pthread_create.c:713 :
      if (pd->stopped_start)

**Comment by ivmai** [comment]
Probably could be caused by a bug in Glibc.

**Comment by ivmai** [comment]
Not reproducible on Ubuntu 20.04.4 LTS (GNU/Linux 4.15.0-74-generic x86_64)
Source: master (c1a6378297)
Test runs: >7000
gcc version: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
glibc version: ldd (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31

But glibc version (2.31) is older than originally reported (2.33).

**Comment by ivmai** [comment]
Source: release-8_2 (cd1fbc1d)
Host: Ubuntu Xenial x64
Link: https://app.travis-ci.com/github/ivmai/bdwgc/jobs/581044040 (rebuilt)

**Comment by ivmai** [comment]
Source: release-8_2 (2b342c4)
Host: Ubuntu Xenial x64
Failed build: https://app.travis-ci.com/github/ivmai/bdwgc/jobs/588637532

**Comment by ivmai** [comment]
Source: master (d389c2d)
Build: https://app.travis-ci.com/github/ivmai/bdwgc/jobs/594219320
Host: Ubuntu 16.04.7 LTS (x64)
Config: CFLAGS_EXTRA="-D _FORTIFY_SOURCE=2 -D FIND_LEAK -D SKIP_LEAKED_OBJECTS_PRINTING" CONF_OPTIONS="--enable-gc-assertions --enable-cplusplus"

**Comment by ivmai** [comment]
Source: master (dac8f77614)
Build: https://app.travis-ci.com/github/ivmai/bdwgc/jobs/595514321
Host: Ubuntu 16.04.7 LTS (x64)
Config: CONF_OPTIONS="--disable-thread-local-alloc --enable-cplusplus --enable-static"

**Comment by ivmai** [comment]
Source: release-8_2 (bef858c)
Build: https://app.travis-ci.com/github/ivmai/bdwgc/jobs/601194715
Host: Ubuntu 16.04.7 LTS / x64
Compiler: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Config: CONF_OPTIONS="--enable-gcov --enable-single-obj-compilation --enable-cplusplus --disable-shared --enable-gc-assertions" CFLAGS_EXTRA="-D USE_CUSTOM_SPECIFIC" CC_FOR_CHECK=g++ MAKEFILE_TARGETS="all" MAKEFILE_TARGETS_CHECK="check"

cat threadkey_test.log:
FAIL threadkey_test (exit status: 139)

**Comment by ivmai** [comment]
Source: release-8_2 (0c12d15)
Build: https://app.travis-ci.com/github/ivmai/bdwgc/jobs/602925319

**Comment by ivmai** [comment]
Source: release-8_2 (964c470)
Build: https://app.travis-ci.com/github/bdwgc/bdwgc/jobs/635920192
Host: Ubuntu 16.04.7 LTS / x64

**Comment by ivmai** [comment]
Source: master (75ef9a302)
Host: Ubuntu 24.04 / x86_64
Reproduced locally.
Build command: `./configure --enable-redirect-malloc --enable-gc-debug --enable-gc-assertions && make -j check CFLAGS_EXTRA="-O3 -march=native"`
Rerun `make -j check` >5 times.

**Comment by ivmai** [comment]
Source: master (83a42e64d)
Host: Ubuntu 24.04 / x86_64
Reproduced locally.
How to reproduce:
`./configure --enable-redirect-malloc --enable-gc-debug --enable-gc-assertions && make -j check CFLAGS_EXTRA="-O0 -g"`
`ulimit -c unlimited`
run `GC_MARKERS=2 ./threadkeytest` many times (> 4000 times)
`coredumpctl info -1`
decompress core file: `zstd -d /var/lib/systemd/coredump/core.threadkeytest.1001.*.zst -o core`
`LD_LIBRARY_PATH=.libs gdb .libs/threadkeytest core`

Core dump inspection:
```
(gdb) t 1
[Switching to thread 1 (Thread 0x76e0dcff96c0 (LWP 2231868))]
#0  0x000076e1919d756e in GC_generic_malloc_inner_small (lb=183, kind=1) at extra/../malloc.c:223
223       *opp = obj_link(op);
(gdb) bt
#0  0x000076e1919d756e in GC_generic_malloc_inner_small (lb=183, kind=1) at extra/../malloc.c:223
#1  0x000076e1919d76bd in GC_generic_malloc_inner (lb=183, kind=1, flags=0) at extra/../malloc.c:237
#2  0x000076e1919cf21d in GC_debug_generic_malloc_inner (lb=64, kind=1, flags=0) at extra/../dbg_mlc.c:562
#3  0x000076e1919f2931 in GC_new_thread (self_id=130708152489664) at extra/../pthread_support.c:807
#4  0x000076e1919f42a9 in GC_register_my_thread_inner (sb=0x76e0dcff8eb0, self_id=130708152489664) at extra/../pthread_support.c:1801
#5  0x000076e1919f7363 in GC_start_rtn_prepare_thread (pstart=0x76e0dcff8df0, pstart_arg=0x76e0dcff8df8, sb=0x76e0dcff8eb0, arg=0x76e0fcff8ce0)
    at extra/../pthread_support.c:2772
#6  0x000076e1919f84e5 in GC_pthread_start_inner (sb=0x76e0dcff8eb0, arg=0x76e0fcff8ce0) at pthread_start.c:57
#7  0x000076e1919f7517 in GC_pthread_start (arg=0x76e0fcff8ce0) at extra/../pthread_support.c:2813
#8  0x000076e19169caa4 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:447
#9  0x000076e191729c6c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
(gdb) p op
$1 = (void *) 0xfffffffffffffff7
```

Note: at each crash the following is the same: lb==183, kind==1, op==~8

**Comment by ivmai** [comment]
Source: master (62a141407)
Build: https://app.travis-ci.com/github/bdwgc/bdwgc/jobs/636486686
Config: `CMAKE_OPTIONS="-Denable_cplusplus=ON -Denable_gc_assertions=ON -Denable_large_config=ON -Denable_redirect_malloc=ON -Denable_rwlock=ON -DCFLAGS_EXTRA=-DIGNORE_FREE"`

**Comment by ivmai** [comment]
Source: master (62a141407)
Build: https://app.travis-ci.com/github/bdwgc/bdwgc/jobs/636486678
Config: `CFLAGS_EXTRA="-D _FORTIFY_SOURCE=2" CONF_OPTIONS="--enable-redirect-malloc --enable-gc-debug --enable-cplusplus --enable-gc-assertions"`

**Comment by ivmai** [comment]
Reproduced locally on release-7_6:
```
#0  GC_unregister_my_thread () at pthread_support.c:1629
1629        GC_ASSERT(me->id == self);
[Current thread is 1 (Thread 0x749f9f7fe6c0 (LWP 228681))]
(gdb) p me
$1 = (GC_thread) 0x0

(gdb) bt
#0  GC_unregister_my_thread () at pthread_support.c:1629
#1  0x000055f5e712e5cd in on_thread_exit_inner (
    sb=<error reading variable: value has been optimized out>,
    arg=0xffff8b5fcaf46cbf,
    arg@entry=<error reading variable: value has been optimized out>)
    at tests/threadkey_test.c:68
#2  0x000074a03511b109 in GC_call_with_stack_base (fn=<optimized out>,
    arg=<optimized out>) at misc.c:1974
#3  0x000074a034e99340 in __GI___nptl_deallocate_tsd ()
    at ./nptl/nptl_deallocate_tsd.c:73
#4  __GI___nptl_deallocate_tsd () at ./nptl/nptl_deallocate_tsd.c:22
#5  0x000074a034e9c890 in start_thread (arg=<optimized out>)
    at ./nptl/pthread_create.c:455
#6  0x000074a034f29c6c in clone3 ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```

**Comment by ivmai** [comment]
Cannot reproduce locally

**Comment by ivmai** [comment]
Build: https://github.com/bdwgc/bdwgc/actions/runs/21468894062/job/61836774544
Source: master (ea7255d41e2)
Host: Ubuntu 24/x86_64
Config: `ubuntu-latest configure --enable-cplusplus --enable-gc-assertions --enable-gc-debug --enable-redirect-malloc gcc -D _FORTIFY_SOURCE=2`
