### ISSUE TITLE
sem_wait in pthread_stop_world.c centos 7 never resumes.

### ISSUE THREAD

**Issue by wyrmwif** [ivmai/bdwgc#249]
Works on multl-thhreaded Centos 6, single-threaded Centos 7, but not multl-thhreaded Centos 7.

=================================configure
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking dependency style of gcc... gcc3
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... gcc
checking if the linker (gcc) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for gcc option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... yes
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (gcc -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... unsupported
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/param.h... yes
checking for getpagesize... yes
checking for working mmap... no
checking for PIC compiler flag... -fPIC
checking whether -fPIC compiler option causes __PIC__ definition... yes
checking whether compiler supports -Wextra... yes
checking whether compiler supports -Wpedantic... yes
checking for pthread_self in -lpthread... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating doc/Makefile
config.status: creating src/Makefile
config.status: creating tests/Makefile
config.status: creating pkgconfig/atomic_ops.pc
config.status: creating pkgconfig/atomic_ops-uninstalled.pc
config.status: creating src/config.h
config.status: executing depfiles commands
config.status: executing libtool commands
config.status: executing default commands

=================================pthread_stop_world.c
    for (i = 0; i < n_live_threads; i++) {
      retry:
{int v; int r=sem_getvalue(&GC_suspend_ack_sem,&v); printf("GC_stop_world sem_wait G %d %d\n", r, v);}
        code = sem_wait(&GC_suspend_ack_sem);
{int v; int r=sem_getvalue(&GC_suspend_ack_sem,&v); printf("GC_stop_world sem_wait H %d %d\n", r, v);}
        if (0 != code) {
          /* On Linux, sem_wait is documented to always return zero.    */
          /* But the documentation appears to be incorrect.             */
          if (errno == EINTR) {
            /* Seems to happen with some versions of gdb.       */
            goto retry;
          }
          ABORT("sem_wait for handler failed");
        }
    }

=================================output
GC_stop_init sem_init J 0 0
GC_stop_world sem_wait G 0 0

**Comment by wyrmwif** [comment]
=================================gdb
(gdb) thread 1
[Switching to thread 1 (Thread 0x7fe5354558c0 (LWP 3987))]
#0  0x00007fe533319d42 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
(gdb) thread 2
[Switching to thread 2 (Thread 0x7fe51a7fc700 (LWP 4018))]
#0  0x00007fe533319d42 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
(gdb) thread 3
[Switching to thread 3 (Thread 0x7fe51affd700 (LWP 4016))]
#0  0x00007fe533319d42 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
(gdb) thread 4
[Switching to thread 4 (Thread 0x7fe51b7fe700 (LWP 4014))]
#0  0x00007fe533319d42 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
(gdb) thread 5
[Switching to thread 5 (Thread 0x7fe51bfff700 (LWP 4012))]
#0  0x00007fe533319d42 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
(gdb) thread 6
[Switching to thread 6 (Thread 0x7fe520ff9700 (LWP 4010))]
#0  0x00007fe533319d42 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
(gdb) thread 7
[Switching to thread 7 (Thread 0x7fe5217fa700 (LWP 4009))]
#0  0x00007fe533319d42 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
(gdb) thread 8
[Switching to thread 8 (Thread 0x7fe521ffb700 (LWP 4008))]
#0  0x00007fe533319d42 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
(gdb) thread 9
[Switching to thread 9 (Thread 0x7fe5227fc700 (LWP 4003))]
#0  0x00007fe533319d42 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
(gdb) thread 10
[Switching to thread 10 (Thread 0x7fe522ffd700 (LWP 4002))]
#0  0x00007fe533319d42 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
(gdb) thread 11
[Switching to thread 11 (Thread 0x7fe5237fe700 (LWP 3998))]
#0  0x00007fe533319d42 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
(gdb) thread 12
[Switching to thread 12 (Thread 0x7fe523fff700 (LWP 3996))]
#0  0x00007fe533319d42 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
(gdb) thread 13
[Switching to thread 13 (Thread 0x7fe530ad8700 (LWP 3994))]
#0  0x00007fe533319d42 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
(gdb) thread 14
[Switching to thread 14 (Thread 0x7fe5312d9700 (LWP 3993))]
#0  0x00007fe533319d42 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
(gdb) thread 15
[Switching to thread 15 (Thread 0x7fe531ada700 (LWP 3992))]
#0  0x00007fe53331bafb in do_futex_wait.constprop.1 () from /lib64/libpthread.so.0
(gdb) bt
#0  0x00007fe53331bafb in do_futex_wait.constprop.1 () from /lib64/libpthread.so.0
#1  0x00007fe53331bb8f in __new_sem_wait_slow.constprop.0 () from /lib64/libpthread.so.0
#2  0x00007fe53331bc2b in sem_wait@@GLIBC_2.2.5 () from /lib64/libpthread.so.0
#3  0x00000000006af023 in GC_stop_world ()
#4  0x00000000006b16c9 in GC_stopped_mark ()
#5  0x00000000006b27ea in GC_try_to_collect_inner ()
#6  0x00000000006b2ff9 in GC_collect_or_expand ()
#7  0x00000000006a06b3 in GC_alloc_large ()
#8  0x00000000006a0b67 in GC_generic_malloc ()
#9  0x00000000006a0f0d in GC_malloc_kind_global ()

**Comment by ivmai** [comment]
Please reproduce with configure --disable-parallel-mark

**Comment by ivmai** [comment]
Is this 100% reproducible? Looks like suspend signal is not delivered. Could you please do "bt" for other threads (with undef PARALLEL_MARK)?
