### ISSUE TITLE
Set name of new threads

### ISSUE THREAD

**Issue by tromey** [ivmai/bdwgc#300]
I noticed that when I start `guile` inside `gdb`, I see a bunch of threads.  When I break on `pthread_create`, I see they come from the GC:

```
(gdb) bt
#0  0x00007ffff77307a0 in pthread_create@@GLIBC_2.2.5 ()
   from /lib64/libpthread.so.0
#1  0x00007ffff7afee49 in GC_start_mark_threads_inner ()
    at pthread_support.c:471
```

However, the threads show up in gdb like:

```
(gdb) info thread
  Id   Target Id                                 Frame 
...
  2    Thread 0x7ffff76fd700 (LWP 21133) "guile" 0x00007ffff77363d5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  3    Thread 0x7ffff6efc700 (LWP 21134) "guile" 0x00007ffff77363d5 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
...
```

I think it would be nice if the GC set the names of these threads to something like '"GC"'.  On Linux and macOS this can be done with `pthread_setname_np` (though be warned that the function takes different arguments on these platforms).

**Comment by ivmai** [comment]
Agree. I could add this for Linux/Android, OS X and, Windows.
(Not sure about the schedule right now, probably I'll do it in January.)

**Comment by ivmai** [comment]
Commits ab91e4e + 294f0b8 is what you've asked about. Please test. Currently works with configure script only.

**Comment by tromey** [comment]
Thank you for doing this.
