### ISSUE TITLE
gctest hangs on NetBSD

### ISSUE THREAD

**Issue by 0-wiz-0** [ivmai/bdwgc#309]
When thread support is enabled on NetBSD (the default), the self tests pass except for gctest; it just hangs.

I'm testing on 9.99.49/amd64. I'm told that it works for a colleague who tested on 9.0/amd64.

When run as `GC_PRINT_VERBOSE_STATS=1 ./gctest`, output ends with:
````
...
Finished mark helper 0
Finished marking for mark phase number 5
GC #6 freed 0 bytes, heap 840 KiB (+ 0 KiB unmapped)
World-stopped marking took 0 ms 0 ns (3 ms in average)
Bytes recovered before sweep - f.l. count = -3840
In-use heap: 0% (1 KiB pointers + 3 KiB other)
Immediately reclaimed -3840 bytes, heapsize: 860160 bytes (0 unmapped)
0 finalization entries; 0/0 short/long disappearing links alive
0 finalization-ready objects; 0/0 short/long links cleared
Finalize and initiate sweep took 0 ms 0 ns + 0 ms 0 ns
Complete collection took 0 ms 0 ns
````

I saw that there are a couple of issues about gctest hanging on various operating systems already, so perhaps there is a bug in the code?

Let me know if there is more debug information I can provide. Thanks.

**Comment by ivmai** [comment]
Please provided stack trace of all threads.

**Comment by 0-wiz-0** [comment]
Sure!
````
Thread 21 (LWP 1 of process 28095):
#0  0x00007cdaa18b026a in ___lwp_park60 () from /usr/lib/libc.so.12
#1  0x00007cdaa240977e in pthread__mutex_lock_slow (ptm=0x7cdaa2a25940 <GC_allocate_ml>, ts=0x0) at /usr/src/lib/libpthread/pthread_mutex.c:390
#2  0x00007cdaa2818ec3 in GC_generic_malloc (lb=1, k=0) at ../extra/../malloc.c:253
#3  0x0000000000404da7 in run_one_test () at ../tests/test.c:1483
#4  0x000000000040599b in main () at ../tests/test.c:2419

Thread 20 (LWP 2 of process 28095):
#0  0x00007cdaa18b026a in ___lwp_park60 () from /usr/lib/libc.so.12
#1  0x00007cdaa240aa90 in pthread_cond_timedwait (cond=0x7cdaa2a26580 <mark_cv>, mutex=0x7cdaa2a25840 <mark_mutex>, abstime=0x0) at /usr/src/lib/libpthread/pthread_cond.c:172
#2  0x00007cdaa280840d in GC_wait_marker () at ../extra/../pthread_support.c:2359
#3  0x00007cdaa280d098 in GC_help_marker (my_mark_no=my_mark_no@entry=8) at ../extra/../mark.c:1244
#4  0x00007cdaa280d16b in GC_mark_thread (id=<optimized out>) at ../extra/../pthread_support.c:413
#5  GC_mark_thread (id=<optimized out>) at ../extra/../pthread_support.c:374
#6  0x00007cdaa240caf2 in pthread__create_tramp (cookie=0x7cdaa2be6000) at /usr/src/lib/libpthread/pthread.c:587
#7  0x00007cdaa188fc60 in ?? () from /usr/lib/libc.so.12
#8  0x0000000000400000 in ?? ()
#9  0x00007cdaa1600000 in ?? ()
#10 0x0000001003a0efff in ?? ()
#11 0x00007cdaa14000c0 in ?? ()
#12 0x00000000001fff40 in ?? ()
#13 0x0000000000000000 in ?? ()

Thread 19 (LWP 3 of process 28095):
#0  0x00007cdaa18b026a in ___lwp_park60 () from /usr/lib/libc.so.12
#1  0x00007cdaa240aa90 in pthread_cond_timedwait (cond=0x7cdaa2a26580 <mark_cv>, mutex=0x7cdaa2a25840 <mark_mutex>, abstime=0x0) at /usr/src/lib/libpthread/pthread_cond.c:172
#2  0x00007cdaa280840d in GC_wait_marker () at ../extra/../pthread_support.c:2359
#3  0x00007cdaa280d098 in GC_help_marker (my_mark_no=my_mark_no@entry=8) at ../extra/../mark.c:1244
#4  0x00007cdaa280d16b in GC_mark_thread (id=<optimized out>) at ../extra/../pthread_support.c:413
#5  GC_mark_thread (id=<optimized out>) at ../extra/../pthread_support.c:374
#6  0x00007cdaa240caf2 in pthread__create_tramp (cookie=0x7cdaa2be4000) at /usr/src/lib/libpthread/pthread.c:587
#7  0x00007cdaa188fc60 in ?? () from /usr/lib/libc.so.12
#8  0x0000000000000000 in ?? ()

Thread 18 (LWP 4 of process 28095):
#0  0x00007cdaa18b026a in ___lwp_park60 () from /usr/lib/libc.so.12
#1  0x00007cdaa240aa90 in pthread_cond_timedwait (cond=0x7cdaa2a26580 <mark_cv>, mutex=0x7cdaa2a25840 <mark_mutex>, abstime=0x0) at /usr/src/lib/libpthread/pthread_cond.c:172
#2  0x00007cdaa280840d in GC_wait_marker () at ../extra/../pthread_support.c:2359
#3  0x00007cdaa280d098 in GC_help_marker (my_mark_no=my_mark_no@entry=8) at ../extra/../mark.c:1244
#4  0x00007cdaa280d16b in GC_mark_thread (id=<optimized out>) at ../extra/../pthread_support.c:413
#5  GC_mark_thread (id=<optimized out>) at ../extra/../pthread_support.c:374
#6  0x00007cdaa240caf2 in pthread__create_tramp (cookie=0x7cdaa2be2000) at /usr/src/lib/libpthread/pthread.c:587
#7  0x00007cdaa188fc60 in ?? () from /usr/lib/libc.so.12
#8  0x0000000000200000 in ?? ()
#9  0x0000000000000000 in ?? ()

Thread 17 (LWP 5 of process 28095):
#0  0x00007cdaa18b026a in ___lwp_park60 () from /usr/lib/libc.so.12
#1  0x00007cdaa240aa90 in pthread_cond_timedwait (cond=0x7cdaa2a26580 <mark_cv>, mutex=0x7cdaa2a25840 <mark_mutex>, abstime=0x0) at /usr/src/lib/libpthread/pthread_cond.c:172
#2  0x00007cdaa280840d in GC_wait_marker () at ../extra/../pthread_support.c:2359
#3  0x00007cdaa280d098 in GC_help_marker (my_mark_no=my_mark_no@entry=8) at ../extra/../mark.c:1244
#4  0x00007cdaa280d16b in GC_mark_thread (id=<optimized out>) at ../extra/../pthread_support.c:413
#5  GC_mark_thread (id=<optimized out>) at ../extra/../pthread_support.c:374
#6  0x00007cdaa240caf2 in pthread__create_tramp (cookie=0x7cdaa2be0000) at /usr/src/lib/libpthread/pthread.c:587
#7  0x00007cdaa188fc60 in ?? () from /usr/lib/libc.so.12
#8  0x0000000000000000 in ?? ()

Thread 16 (LWP 6 of process 28095):
#0  0x00007cdaa18b026a in ___lwp_park60 () from /usr/lib/libc.so.12
#1  0x00007cdaa240aa90 in pthread_cond_timedwait (cond=0x7cdaa2a26580 <mark_cv>, mutex=0x7cdaa2a25840 <mark_mutex>, abstime=0x0) at /usr/src/lib/libpthread/pthread_cond.c:172
#2  0x00007cdaa280840d in GC_wait_marker () at ../extra/../pthread_support.c:2359
#3  0x00007cdaa280d098 in GC_help_marker (my_mark_no=my_mark_no@entry=8) at ../extra/../mark.c:1244
#4  0x00007cdaa280d16b in GC_mark_thread (id=<optimized out>) at ../extra/../pthread_support.c:413
#5  GC_mark_thread (id=<optimized out>) at ../extra/../pthread_support.c:374
#6  0x00007cdaa240caf2 in pthread__create_tramp (cookie=0x7cdaa2bde000) at /usr/src/lib/libpthread/pthread.c:587
#7  0x00007cdaa188fc60 in ?? () from /usr/lib/libc.so.12
#8  0x0000000000200000 in ?? ()
#9  0x0000000000000000 in ?? ()

Thread 15 (LWP 7 of process 28095):
#0  0x00007cdaa18b026a in ___lwp_park60 () from /usr/lib/libc.so.12
#1  0x00007cdaa240aa90 in pthread_cond_timedwait (cond=0x7cdaa2a26580 <mark_cv>, mutex=0x7cdaa2a25840 <mark_mutex>, abstime=0x0) at /usr/src/lib/libpthread/pthread_cond.c:172
#2  0x00007cdaa280840d in GC_wait_marker () at ../extra/../pthread_support.c:2359
#3  0x00007cdaa280d098 in GC_help_marker (my_mark_no=my_mark_no@entry=8) at ../extra/../mark.c:1244
#4  0x00007cdaa280d16b in GC_mark_thread (id=<optimized out>) at ../extra/../pthread_support.c:413
#5  GC_mark_thread (id=<optimized out>) at ../extra/../pthread_support.c:374
#6  0x00007cdaa240caf2 in pthread__create_tramp (cookie=0x7cdaa2bdc000) at /usr/src/lib/libpthread/pthread.c:587
#7  0x00007cdaa188fc60 in ?? () from /usr/lib/libc.so.12
#8  0x0000000000200000 in ?? ()
#9  0x0000000000000000 in ?? ()

Thread 14 (LWP 8 of process 28095):
#0  0x00007cdaa18b026a in ___lwp_park60 () from /usr/lib/libc.so.12
#1  0x00007cdaa240aa90 in pthread_cond_timedwait (cond=0x7cdaa2a26580 <mark_cv>, mutex=0x7cdaa2a25840 <mark_mutex>, abstime=0x0) at /usr/src/lib/libpthread/pthread_cond.c:172
#2  0x00007cdaa280840d in GC_wait_marker () at ../extra/../pthread_support.c:2359
#3  0x00007cdaa280d098 in GC_help_marker (my_mark_no=my_mark_no@entry=8) at ../extra/../mark.c:1244
#4  0x00007cdaa280d16b in GC_mark_thread (id=<optimized out>) at ../extra/../pthread_support.c:413
#5  GC_mark_thread (id=<optimized out>) at ../extra/../pthread_support.c:374
#6  0x00007cdaa240caf2 in pthread__create_tramp (cookie=0x7cdaa2bda000) at /usr/src/lib/libpthread/pthread.c:587
#7  0x00007cdaa188fc60 in ?? () from /usr/lib/libc.so.12
#8  0x0000000000200000 in ?? ()
#9  0x0000000000000000 in ?? ()

Thread 13 (LWP 9 of process 28095):
#0  0x00007cdaa18b026a in ___lwp_park60 () from /usr/lib/libc.so.12
#1  0x00007cdaa240aa90 in pthread_cond_timedwait (cond=0x7cdaa2a26580 <mark_cv>, mutex=0x7cdaa2a25840 <mark_mutex>, abstime=0x0) at /usr/src/lib/libpthread/pthread_cond.c:172
#2  0x00007cdaa280840d in GC_wait_marker () at ../extra/../pthread_support.c:2359
#3  0x00007cdaa280d098 in GC_help_marker (my_mark_no=my_mark_no@entry=8) at ../extra/../mark.c:1244
#4  0x00007cdaa280d16b in GC_mark_thread (id=<optimized out>) at ../extra/../pthread_support.c:413
#5  GC_mark_thread (id=<optimized out>) at ../extra/../pthread_support.c:374
#6  0x00007cdaa240caf2 in pthread__create_tramp (cookie=0x7cdaa2bd8000) at /usr/src/lib/libpthread/pthread.c:587
#7  0x00007cdaa188fc60 in ?? () from /usr/lib/libc.so.12
#8  0x0000000000000000 in ?? ()

Thread 12 (LWP 10 of process 28095):
#0  0x00007cdaa18b026a in ___lwp_park60 () from /usr/lib/libc.so.12
#1  0x00007cdaa240aa90 in pthread_cond_timedwait (cond=0x7cdaa2a26580 <mark_cv>, mutex=0x7cdaa2a25840 <mark_mutex>, abstime=0x0) at /usr/src/lib/libpthread/pthread_cond.c:172
#2  0x00007cdaa280840d in GC_wait_marker () at ../extra/../pthread_support.c:2359
#3  0x00007cdaa280d098 in GC_help_marker (my_mark_no=my_mark_no@entry=8) at ../extra/../mark.c:1244
#4  0x00007cdaa280d16b in GC_mark_thread (id=<optimized out>) at ../extra/../pthread_support.c:413
#5  GC_mark_thread (id=<optimized out>) at ../extra/../pthread_support.c:374
#6  0x00007cdaa240caf2 in pthread__create_tramp (cookie=0x7cdaa2bd6000) at /usr/src/lib/libpthread/pthread.c:587
#7  0x00007cdaa188fc60 in ?? () from /usr/lib/libc.so.12
#8  0x0000000000000000 in ?? ()

Thread 11 (LWP 11 of process 28095):
#0  0x00007cdaa18b026a in ___lwp_park60 () from /usr/lib/libc.so.12
#1  0x00007cdaa240aa90 in pthread_cond_timedwait (cond=0x7cdaa2a26580 <mark_cv>, mutex=0x7cdaa2a25840 <mark_mutex>, abstime=0x0) at /usr/src/lib/libpthread/pthread_cond.c:172
#2  0x00007cdaa280840d in GC_wait_marker () at ../extra/../pthread_support.c:2359
#3  0x00007cdaa280d098 in GC_help_marker (my_mark_no=my_mark_no@entry=8) at ../extra/../mark.c:1244
#4  0x00007cdaa280d16b in GC_mark_thread (id=<optimized out>) at ../extra/../pthread_support.c:413
#5  GC_mark_thread (id=<optimized out>) at ../extra/../pthread_support.c:374
#6  0x00007cdaa240caf2 in pthread__create_tramp (cookie=0x7cdaa2bd4000) at /usr/src/lib/libpthread/pthread.c:587
#7  0x00007cdaa188fc60 in ?? () from /usr/lib/libc.so.12
#8  0x0000000000000000 in ?? ()

Thread 10 (LWP 12 of process 28095):
#0  0x00007cdaa18b026a in ___lwp_park60 () from /usr/lib/libc.so.12
#1  0x00007cdaa240aa90 in pthread_cond_timedwait (cond=0x7cdaa2a26580 <mark_cv>, mutex=0x7cdaa2a25840 <mark_mutex>, abstime=0x0) at /usr/src/lib/libpthread/pthread_cond.c:172
#2  0x00007cdaa280840d in GC_wait_marker () at ../extra/../pthread_support.c:2359
#3  0x00007cdaa280d098 in GC_help_marker (my_mark_no=my_mark_no@entry=8) at ../extra/../mark.c:1244
#4  0x00007cdaa280d16b in GC_mark_thread (id=<optimized out>) at ../extra/../pthread_support.c:413
#5  GC_mark_thread (id=<optimized out>) at ../extra/../pthread_support.c:374
#6  0x00007cdaa240caf2 in pthread__create_tramp (cookie=0x7cdaa2b6f000) at /usr/src/lib/libpthread/pthread.c:587
#7  0x00007cdaa188fc60 in ?? () from /usr/lib/libc.so.12
#8  0x0000000000000000 in ?? ()

Thread 9 (LWP 13 of process 28095):
#0  0x00007cdaa18b026a in ___lwp_park60 () from /usr/lib/libc.so.12
#1  0x00007cdaa240aa90 in pthread_cond_timedwait (cond=0x7cdaa2a26580 <mark_cv>, mutex=0x7cdaa2a25840 <mark_mutex>, abstime=0x0) at /usr/src/lib/libpthread/pthread_cond.c:172
#2  0x00007cdaa280840d in GC_wait_marker () at ../extra/../pthread_support.c:2359
#3  0x00007cdaa280d098 in GC_help_marker (my_mark_no=my_mark_no@entry=8) at ../extra/../mark.c:1244
#4  0x00007cdaa280d16b in GC_mark_thread (id=<optimized out>) at ../extra/../pthread_support.c:413
#5  GC_mark_thread (id=<optimized out>) at ../extra/../pthread_support.c:374
#6  0x00007cdaa240caf2 in pthread__create_tramp (cookie=0x7cdaa2b6d000) at /usr/src/lib/libpthread/pthread.c:587
#7  0x00007cdaa188fc60 in ?? () from /usr/lib/libc.so.12
#8  0x0000000000200000 in ?? ()
#9  0x0000000000000000 in ?? ()

Thread 8 (LWP 14 of process 28095):
#0  0x00007cdaa18b026a in ___lwp_park60 () from /usr/lib/libc.so.12
#1  0x00007cdaa240aa90 in pthread_cond_timedwait (cond=0x7cdaa2a26580 <mark_cv>, mutex=0x7cdaa2a25840 <mark_mutex>, abstime=0x0) at /usr/src/lib/libpthread/pthread_cond.c:172
#2  0x00007cdaa280840d in GC_wait_marker () at ../extra/../pthread_support.c:2359
#3  0x00007cdaa280d098 in GC_help_marker (my_mark_no=my_mark_no@entry=8) at ../extra/../mark.c:1244
#4  0x00007cdaa280d16b in GC_mark_thread (id=<optimized out>) at ../extra/../pthread_support.c:413
#5  GC_mark_thread (id=<optimized out>) at ../extra/../pthread_support.c:374
#6  0x00007cdaa240caf2 in pthread__create_tramp (cookie=0x7cdaa2b6b000) at /usr/src/lib/libpthread/pthread.c:587
#7  0x00007cdaa188fc60 in ?? () from /usr/lib/libc.so.12
#8  0x0000000000000000 in ?? ()

Thread 7 (LWP 15 of process 28095):
#0  0x00007cdaa18b026a in ___lwp_park60 () from /usr/lib/libc.so.12
#1  0x00007cdaa240aa90 in pthread_cond_timedwait (cond=0x7cdaa2a26580 <mark_cv>, mutex=0x7cdaa2a25840 <mark_mutex>, abstime=0x0) at /usr/src/lib/libpthread/pthread_cond.c:172
#2  0x00007cdaa280840d in GC_wait_marker () at ../extra/../pthread_support.c:2359
#3  0x00007cdaa280d098 in GC_help_marker (my_mark_no=my_mark_no@entry=8) at ../extra/../mark.c:1244
#4  0x00007cdaa280d16b in GC_mark_thread (id=<optimized out>) at ../extra/../pthread_support.c:413
#5  GC_mark_thread (id=<optimized out>) at ../extra/../pthread_support.c:374
#6  0x00007cdaa240caf2 in pthread__create_tramp (cookie=0x7cdaa2b69000) at /usr/src/lib/libpthread/pthread.c:587
#7  0x00007cdaa188fc60 in ?? () from /usr/lib/libc.so.12
#8  0x0000000000200000 in ?? ()
#9  0x0000000000000000 in ?? ()

Thread 6 (LWP 16 of process 28095):
#0  0x00007cdaa18b026a in ___lwp_park60 () from /usr/lib/libc.so.12
#1  0x00007cdaa240aa90 in pthread_cond_timedwait (cond=0x7cdaa2a26580 <mark_cv>, mutex=0x7cdaa2a25840 <mark_mutex>, abstime=0x0) at /usr/src/lib/libpthread/pthread_cond.c:172
#2  0x00007cdaa280840d in GC_wait_marker () at ../extra/../pthread_support.c:2359
#3  0x00007cdaa280d098 in GC_help_marker (my_mark_no=my_mark_no@entry=8) at ../extra/../mark.c:1244
#4  0x00007cdaa280d16b in GC_mark_thread (id=<optimized out>) at ../extra/../pthread_support.c:413
#5  GC_mark_thread (id=<optimized out>) at ../extra/../pthread_support.c:374
#6  0x00007cdaa240caf2 in pthread__create_tramp (cookie=0x7cdaa2b67000) at /usr/src/lib/libpthread/pthread.c:587
#7  0x00007cdaa188fc60 in ?? () from /usr/lib/libc.so.12
#8  0x0000000000200000 in ?? ()
#9  0x0000000000000000 in ?? ()

Thread 5 (LWP 17 of process 28095):
#0  0x00007cdaa18b026a in ___lwp_park60 () from /usr/lib/libc.so.12
#1  0x00007cdaa240977e in pthread__mutex_lock_slow (ptm=ptm@entry=0x7cdaa26126a0, ts=ts@entry=0x0) at /usr/src/lib/libpthread/pthread_mutex.c:390
#2  0x00007cdaa2409b67 in pthread_mutex_lock (ptm=0x7cdaa26126a0) at /usr/src/lib/libpthread/pthread_mutex.c:214
#3  pthread_mutex_lock (ptm=ptm@entry=0x7cdaa26126a0) at /usr/src/lib/libpthread/pthread_mutex.c:195
#4  0x00007cdaa24084a0 in pthread__add_specific (self=0x7cdaa2b65000, key=0, value=0x7cdaa2b39048) at /usr/src/lib/libpthread/pthread_tsd.c:190
#5  0x00007cdaa2408946 in pthread_setspecific (key=<optimized out>, value=<optimized out>) at /usr/src/lib/libpthread/pthread_specific.c:69
#6  0x00007cdaa18bda05 in tsd_set (val=0x7cdaa2b39048) at /usr/src/external/bsd/jemalloc/lib/../include/jemalloc/internal/tsd_tls.h:53
#7  je_tsd_fetch_slow (tsd=tsd@entry=0x7cdaa2b39048, minimal=minimal@entry=false) at /usr/src/external/bsd/jemalloc/lib/../dist/src/tsd.c:133
#8  0x00007cdaa1919331 in tsd_fetch_impl (minimal=false, init=true) at /usr/src/external/bsd/jemalloc/lib/../include/jemalloc/internal/tsd.h:265
#9  tsd_fetch () at /usr/src/external/bsd/jemalloc/lib/../include/jemalloc/internal/tsd.h:291
#10 je_jemalloc_prefork () at /usr/src/external/bsd/jemalloc/lib/../dist/src/jemalloc.c:3243
#11 0x00007cdaa197d896 in _fork () at /usr/src/lib/libc/gen/pthread_atfork.c:158
#12 0x0000000000405057 in run_one_test () at ../tests/test.c:1512
#13 0x0000000000405460 in thr_run_one_test (arg=arg@entry=0x0) at ../tests/test.c:2325
#14 0x00007cdaa28178e0 in GC_inner_start_routine (sb=<error reading variable: value has been optimized out>, arg=0x7f7fff5e46b0, arg@entry=<error reading variable: value has been optimized out>) at ../extra/../pthread_start.c:57
#15 0x00007cdaa2810d19 in GC_call_with_stack_base (fn=<optimized out>, arg=<optimized out>) at ../extra/../misc.c:2130
#16 0x00007cdaa240caf2 in pthread__create_tramp (cookie=0x7cdaa2b65000) at /usr/src/lib/libpthread/pthread.c:587
#17 0x00007cdaa188fc60 in ?? () from /usr/lib/libc.so.12
#18 0x0000000000200000 in ?? ()
#19 0x0000000000000000 in ?? ()

Thread 4 (LWP 18 of process 28095):
#0  0x00007cdaa18b026a in ___lwp_park60 () from /usr/lib/libc.so.12
#1  0x00007cdaa240977e in pthread__mutex_lock_slow (ptm=0x7cdaa2a25940 <GC_allocate_ml>, ts=0x0) at /usr/src/lib/libpthread/pthread_mutex.c:390
#2  0x00007cdaa280e042 in GC_free (p=0x7cdaa27ebeb0) at ../extra/../malloc.c:601
#3  0x0000000000404d82 in run_one_test () at ../tests/test.c:1480
#4  0x0000000000405460 in thr_run_one_test (arg=arg@entry=0x0) at ../tests/test.c:2325
#5  0x00007cdaa28178e0 in GC_inner_start_routine (sb=<error reading variable: value has been optimized out>, arg=0x7f7fff5e46b0, arg@entry=<error reading variable: value has been optimized out>) at ../extra/../pthread_start.c:57
#6  0x00007cdaa2810d19 in GC_call_with_stack_base (fn=<optimized out>, arg=<optimized out>) at ../extra/../misc.c:2130
#7  0x00007cdaa240caf2 in pthread__create_tramp (cookie=0x7cdaa2b63000) at /usr/src/lib/libpthread/pthread.c:587
#8  0x00007cdaa188fc60 in ?? () from /usr/lib/libc.so.12
#9  0x0000000000000000 in ?? ()

Thread 3 (LWP 19 of process 28095):
#0  0x00007cdaa18b026a in ___lwp_park60 () from /usr/lib/libc.so.12
#1  0x00007cdaa240977e in pthread__mutex_lock_slow (ptm=0x7cdaa2a25940 <GC_allocate_ml>, ts=0x0) at /usr/src/lib/libpthread/pthread_mutex.c:390
#2  0x00007cdaa2818ec3 in GC_generic_malloc (lb=1, k=0) at ../extra/../malloc.c:253
#3  0x0000000000404da7 in run_one_test () at ../tests/test.c:1483
#4  0x0000000000405460 in thr_run_one_test (arg=arg@entry=0x0) at ../tests/test.c:2325
#5  0x00007cdaa28178e0 in GC_inner_start_routine (sb=<error reading variable: value has been optimized out>, arg=0x7f7fff5e46b0, arg@entry=<error reading variable: value has been optimized out>) at ../extra/../pthread_start.c:57
#6  0x00007cdaa2810d19 in GC_call_with_stack_base (fn=<optimized out>, arg=<optimized out>) at ../extra/../misc.c:2130
#7  0x00007cdaa240caf2 in pthread__create_tramp (cookie=0x7cdaa2b61000) at /usr/src/lib/libpthread/pthread.c:587
#8  0x00007cdaa188fc60 in ?? () from /usr/lib/libc.so.12
#9  0x0000000000000000 in ?? ()

Thread 2 (LWP 20 of process 28095):
#0  0x00007cdaa18b026a in ___lwp_park60 () from /usr/lib/libc.so.12
#1  0x00007cdaa240977e in pthread__mutex_lock_slow (ptm=0x7cdaa2a25940 <GC_allocate_ml>, ts=0x0) at /usr/src/lib/libpthread/pthread_mutex.c:390
#2  0x00007cdaa2818ec3 in GC_generic_malloc (lb=2, k=1) at ../extra/../malloc.c:253
#3  0x0000000000404db9 in run_one_test () at ../tests/test.c:1484
#4  0x0000000000405460 in thr_run_one_test (arg=arg@entry=0x0) at ../tests/test.c:2325
#5  0x00007cdaa28178e0 in GC_inner_start_routine (sb=<error reading variable: value has been optimized out>, arg=0x7f7fff5e46b0, arg@entry=<error reading variable: value has been optimized out>) at ../extra/../pthread_start.c:57
#6  0x00007cdaa2810d19 in GC_call_with_stack_base (fn=<optimized out>, arg=<optimized out>) at ../extra/../misc.c:2130
#7  0x00007cdaa240caf2 in pthread__create_tramp (cookie=0x7cdaa2b5f000) at /usr/src/lib/libpthread/pthread.c:587
#8  0x00007cdaa188fc60 in ?? () from /usr/lib/libc.so.12
#9  0x0000000000000000 in ?? ()

Thread 1 (LWP 21 of process 28095):
#0  0x00007cdaa18b026a in ___lwp_park60 () from /usr/lib/libc.so.12
#1  0x00007cdaa240977e in pthread__mutex_lock_slow (ptm=0x7cdaa2a25940 <GC_allocate_ml>, ts=0x0) at /usr/src/lib/libpthread/pthread_mutex.c:390
#2  0x00007cdaa280e042 in GC_free (p=p@entry=0x7cdaa2af4180) at ../extra/../malloc.c:601
#3  0x0000000000403bc0 in test_generic_malloc_or_special (p=<optimized out>) at ../tests/test.c:697
#4  0x0000000000404d94 in run_one_test () at ../tests/test.c:1481
#5  0x0000000000405460 in thr_run_one_test (arg=arg@entry=0x0) at ../tests/test.c:2325
#6  0x00007cdaa28178e0 in GC_inner_start_routine (sb=<error reading variable: value has been optimized out>, arg=0x7f7fff5e46b0, arg@entry=<error reading variable: value has been optimized out>) at ../extra/../pthread_start.c:57
#7  0x00007cdaa2810d19 in GC_call_with_stack_base (fn=<optimized out>, arg=<optimized out>) at ../extra/../misc.c:2130
#8  0x00007cdaa240caf2 in pthread__create_tramp (cookie=0x7cdaa2b5d000) at /usr/src/lib/libpthread/pthread.c:587
#9  0x00007cdaa188fc60 in ?? () from /usr/lib/libc.so.12
#10 0x0000000000000000 in ?? ()
````

**Comment by ivmai** [comment]
Hello @0-wiz-0 ,
Is this still reproducible on latest master?

```
Thread 5 (LWP 17 of process 28095):
#0  0x00007cdaa18b026a in ___lwp_park60 () from /usr/lib/libc.so.12
#1  0x00007cdaa240977e in pthread__mutex_lock_slow (ptm=ptm@entry=0x7cdaa26126a0, ts=ts@entry=0x0) at /usr/src/lib/libpthread/pthread_mutex.c:390
```
This thread seems to acquire the lock, but what's thread owning it?

**Comment by 0-wiz-0** [comment]
I just tried latest git head and it worked fine!
```
gmake[3]: Entering directory '/disk/6/archive/foreign/bdwgc/build'
PASS: cordtest
PASS: gctest
PASS: hugetest
PASS: leaktest
PASS: middletest
PASS: realloctest
PASS: smashtest
PASS: staticrootstest
PASS: atomicopstest
PASS: initfromthreadtest
PASS: subthreadcreatetest
PASS: threadkeytest
PASS: threadleaktest
PASS: disclaimtest
PASS: disclaim_bench
PASS: weakmaptest
============================================================================
Testsuite summary for gc 8.3.0
============================================================================
```
Thanks!
