### ISSUE TITLE
SIGSEGV in gctest, disclaimtest, weakmaptest if compiled with TSan and MPROTECT_VDB mode active on Linux

### ISSUE THREAD

**Issue by ivmai** [ivmai/bdwgc#550]
Source: master (7334cc94a04b)
Host: Linux 5.15.0-69-generic / x86_64
Compiler: gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
How to build: ./configure --enable-static && make -j check CFLAGS_EXTRA="-O3 -fsanitize=thread -fno-omit-frame-pointer -D NO_SOFT_VDB"

cat gctest.log
Switched to incremental mode
Emulating dirty bits with mprotect/signals
FAIL gctest (exit status: 139)

**Comment by ivmai** [comment]
How to see the stack trace:
ulimit -c unlimited
sudo service apport start
make -j check
sudo coredumpctl debug .libs/gctest
```
Program terminated with signal SIGSEGV, Segmentation fault.
(gdb) bt
#0  0x00007fe04cc42b74 in __sanitizer::atomic_store<__sanitizer::atomic_uint64_t> (mo=__sanitizer::memory_order_release, v=7, a=0x7fe04b61fc20)
    at ../../../../src/libsanitizer/sanitizer_common/sanitizer_atomic_clang_x86.h:85
#1  __sanitizer::atomic_store<__sanitizer::atomic_uint64_t> (mo=__sanitizer::memory_order_release, v=7, a=0x7fe04b61fc20)
    at ../../../../src/libsanitizer/sanitizer_common/sanitizer_atomic_clang_x86.h:73
#2  NoTsanAtomicStore<unsigned long long> (mo=__tsan::mo_release, v=7, a=0x7fe04b61fc20) at ../../../../src/libsanitizer/tsan/tsan_interface_atomic.cpp:247
#3  AtomicStore<unsigned long long> (mo=<optimized out>, v=7, a=0x7fe04b61fc20, pc=140601337326079, thr=0x7fe0425b8ac0) at ../../../../src/libsanitizer/tsan/tsan_interface_atomic.cpp:276
#4  __tsan_atomic64_store (a=a@entry=0x7fe04b61fc20, v=v@entry=7, mo=<optimized out>, mo@entry=__tsan::mo_release) at ../../../../src/libsanitizer/tsan/tsan_interface_atomic.cpp:566
#5  0x00007fe04cb6d9da in GC_suspend_handler_inner (dummy=0x0, context=<optimized out>) at pthread_stop_world.c:429
#6  GC_suspend_sigaction (sig=<optimized out>, info=<optimized out>, context=<optimized out>) at pthread_stop_world.c:276
#7  0x00007fe04cbef7f7 in __tsan::CallUserSignalHandler (thr=thr@entry=0x7fe0425b8ac0, sync=<optimized out>, acquire=acquire@entry=true, sigact=sigact@entry=true, sig=sig@entry=31,
    info=info@entry=0x7fe0425b7230, uctx=0x7fe0425b7100) at ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:1922
#8  0x00007fe04cbf1df5 in rtl_generic_sighandler (ctx=0x7fe0425b7100, info=0x7fe0425b7230, sig=31, sigact=true) at ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:2016
#9  rtl_sigaction (sig=<optimized out>, info=0x7fe0425b7230, ctx=0x7fe0425b7100) at ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:2041
#10 <signal handler called>
#11 __sanitizer::atomic_store<__sanitizer::atomic_uint64_t> (mo=__sanitizer::memory_order_relaxed, v=18119951625808324, a=0xf812c93a000)
    at ../../../../src/libsanitizer/sanitizer_common/sanitizer_atomic_clang_x86.h:73
#12 __tsan::StoreShadow (s=18119951625808324, sp=0xf812c93a000) at ../../../../src/libsanitizer/tsan/tsan_rtl.cpp:627
#13 __tsan::StoreIfNotYetStored (s=<synthetic pointer>, sp=0xf812c93a000) at ../../../../src/libsanitizer/tsan/tsan_rtl.cpp:632
#14 __tsan::MemoryAccessImpl1 (cur=..., shadow_mem=0xf812c93a000, kIsAtomic=false, kAccessIsWrite=true, kAccessSizeLog=<optimized out>, addr=<optimized out>, thr=0x7fe0425b8ac0)
    at ../../../../src/libsanitizer/tsan/tsan_update_shadow_word_inl.h:43
#15 __tsan::MemoryAccessImpl (thr=thr@entry=0x7fe0425b8ac0, addr=<optimized out>, kAccessSizeLog=kAccessSizeLog@entry=3, kAccessIsWrite=kAccessIsWrite@entry=true,
    kIsAtomic=kIsAtomic@entry=false, shadow_mem=shadow_mem@entry=0xf812c93a000, cur=...) at ../../../../src/libsanitizer/tsan/tsan_rtl.cpp:910
#16 0x00007fe04cc689f3 in __tsan::MemoryAccessRange (thr=thr@entry=0x7fe0425b8ac0, pc=<optimized out>, addr=<optimized out>, addr@entry=140601310109712, size=<optimized out>,
    size@entry=8176, is_write=is_write@entry=true) at ../../../../src/libsanitizer/tsan/tsan_rtl_thread.cpp:411
#17 0x00007fe04cc23570 in __interceptor_memset (size=8176, v=0, dst=0x7fe04b24e010) at ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:799
#18 __interceptor_memset (dst=dst@entry=0x7fe04b24e010, v=v@entry=0, size=size@entry=8176) at ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:797
#19 0x00007fe04cb556d0 in memset (__len=8176, __ch=0, __dest=0x7fe04b24e010) at /usr/include/x86_64-linux-gnu/bits/string_fortified.h:59
#20 GC_generic_malloc_aligned (lb=<optimized out>, lb@entry=4096, k=k@entry=1, flags=flags@entry=0, align_m1=align_m1@entry=4095) at malloc.c:295
#21 0x00007fe04cb574d2 in GC_memalign (align=4096, lb=4096) at mallocx.c:479
#22 0x00007fe04cb57689 in GC_pvalloc (lb=<optimized out>, lb@entry=123) at mallocx.c:541
#23 0x000055c0ff581e0d in run_one_test () at tests/gctest.c:1661
#24 0x000055c0ff58290c in thr_run_one_test (arg=<optimized out>) at tests/gctest.c:2535
#25 0x00007fe04cb694d8 in GC_pthread_start_inner (sb=sb@entry=0x7fe0425b81b0, arg=arg@entry=0x7fff37972070) at pthread_start.c:55
#26 0x00007fe04cb5efe7 in GC_call_with_stack_base (fn=0x7fe04cb69430 <GC_pthread_start_inner>, arg=arg@entry=0x7fff37972070) at misc.c:2180
#27 0x00007fe04cb698f9 in GC_pthread_start (arg=0x7fff37972070) at pthread_support.c:2425
#28 0x00007fe04cbf0600 in __tsan_thread_start_func (arg=0x7fff37971f60) at ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:959
#29 0x00007fe04c981b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#30 0x00007fe04ca13a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

**Comment by ivmai** [comment]
The following draft patch helps only for weakmaptest (probably helps):
Unprotect thread struct before signal sent:
```
diff --git a/include/private/pthread_support.h b/include/private/pthread_support.h
index fa0d0789..6d42b24b 100644
--- a/include/private/pthread_support.h
+++ b/include/private/pthread_support.h
@@ -364,6 +364,8 @@ GC_EXTERN GC_thread GC_threads[THREAD_TABLE_SZ];
 # define GC_win32_dll_threads FALSE
 #endif /* !GC_WIN32_THREADS */
 
+GC_INNER void GC_win32_unprotect_thread(GC_thread);//??
+
 #ifdef GC_PTHREADS
 # if defined(GC_WIN32_THREADS) && !defined(CYGWIN32) \
      && (defined(GC_WIN32_PTHREADS) || defined(GC_PTHREADS_PARAMARK)) \
diff --git a/pthread_stop_world.c b/pthread_stop_world.c
index 16216ecb..3c05e5d9 100644
--- a/pthread_stop_world.c
+++ b/pthread_stop_world.c
@@ -579,6 +579,7 @@ STATIC void GC_restart_handler(int sig)
       for (retry = 0; ; retry++)
 #   endif
     {
+GC_win32_unprotect_thread(p);//??
 #     ifdef USE_TKILL_ON_ANDROID
         int old_errno = errno;
 
diff --git a/pthread_support.c b/pthread_support.c
index c1232cef..d6e9d95d 100644
--- a/pthread_support.c
+++ b/pthread_support.c
@@ -647,10 +647,10 @@ void GC_push_thread_structures(void)
 # endif
 }
 
-#if defined(MPROTECT_VDB) && defined(GC_WIN32_THREADS)
+#if defined(MPROTECT_VDB) //&& defined(GC_WIN32_THREADS) ??
   GC_INNER void GC_win32_unprotect_thread(GC_thread t)
   {
-    if (!GC_win32_dll_threads && GC_auto_incremental) {
+    if (/*!GC_win32_dll_threads &&*/ GC_auto_incremental) {
       GC_stack_context_t crtn = t -> crtn;
 
       if (crtn != &first_crtn) {
```
