### ISSUE TITLE
SIGSEGV in gctest on Linux/x64 if redirect malloc

### ISSUE THREAD

**Issue by ivmai** [ivmai/bdwgc#582]
Source: master (57be9268a)
Build: https://github.com/ivmai/bdwgc/actions/runs/6803906533/job/18500277982
Config: ubuntu-latest clang thr:on redir:on dll:off
How to build: `cmake -DBUILD_SHARED_LIBS=off -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=Release -Dbuild_tests=ON -Ddisable_gc_debug=off -Denable_gc_assertions=off -Denable_large_config=off -Denable_redirect_malloc=on .. && cmake --build . && ctest`
Occurrence: sometimes
Output:
```
GC Warning: USE_PROC_FOR_LIBRARIES + GC_LINUX_THREADS performs poorly
GC Warning: Heap grown by 72 KiB while GC was disabled
GC Warning: Heap grown by 1456 KiB while GC was disabled
GC Warning: Heap grown by 3572 KiB while GC was disabled
GC Warning: Heap grown by 688 KiB while GC was disabled

*Exception: SegFault  2.44 sec
```

**Comment by ivmai** [comment]
Source: master (602c93ab)
Build: https://github.com/ivmai/bdwgc/actions/runs/7049503020/job/19188122673

**Comment by ivmai** [comment]
Source: master (f369491)
Build: https://github.com/ivmai/bdwgc/actions/runs/7143780329/job/19456020138

**Comment by ivmai** [comment]
Reproduce locally (with -O0). Occurrence: ~1/10
Source: master (https://github.com/ivmai/bdwgc/commit/f369491aa2ea1ba9d7e123400cda13854ff37d2a)
```
#0  GC_check_finalizer_nested () at pthread_support.c:854
#1  0x0000555555560f04 in GC_notify_or_invoke_finalizers () at finalize.c:1390
#2  0x000055555556226e in GC_generic_malloc_aligned (lb=lb@entry=32, k=k@entry=1, flags=flags@entry=0,
    align_m1=align_m1@entry=0) at malloc.c:232
#3  0x000055555556266a in GC_malloc_kind_aligned_global (lb=32, k=1, align_m1=0) at malloc.c:352
#4  0x00007ffff7f99b7a in pthread_getattr_np (thread_id=<optimized out>, attr=attr@entry=0x7fffedbc2e70)
    at pthread_getattr_np.c:176
#5  0x000055555556a400 in GC_get_stack_base (b=b@entry=0x7fffedbc2ed8) at os_dep.c:1363
#6  0x000055555556d5bc in GC_pthread_start (arg=0x7fffee51c4e0) at pthread_support.c:2491
#7  0x00007ffff7f97ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#8  0x00007ffff7eb1a2f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
